doc-valid-idents = [
    "BonsaiDb",
    "WebSockets",
    "WebAssembly",
    # Defaults from Clippy follow:
    "KiB",
    "MiB",
    "GiB",
    "TiB",
    "PiB",
    "EiB",
    "DirectX",
    "ECMAScript",
    "GPLv2",
    "GPLv3",
    "GitHub",
    "GitLab",
    "IPv4",
    "IPv6",
    "ClojureScript",
    "CoffeeScript",
    "JavaScript",
    "PureScript",
    "TypeScript",
    "NaN",
    "NaNs",
    "OAuth",
    "GraphQL",
    "OCaml",
    "OpenGL",
    "OpenMP",
    "OpenSSH",
    "OpenSSL",
    "OpenStreetMap",
    "OpenDNS",
    "WebGL",
    "TensorFlow",
    "TrueType",
    "iOS",
    "macOS",
    "FreeBSD",
    "TeX",
    "LaTeX",
    "BibTeX",
    "BibLaTeX",
    "MinGW",
    "CamelCase",
]
