[book]
authors = ["Jonathan Johnson"]
language = "en"
multilingual = false
src = "src"
title = "BonsaiDb User's Guide"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[output.linkcheck]
follow-web-links = true

[preprocessor.variables]
use_env = true

[preprocessor.variables.variables]
DOCS_BASE_URL = "https://dev.bonsaidb.io/release/docs"

[output.linkcheck.http-headers]
# Any hyperlink that contains this regexp will be sent
# the "Accept: text/html" header
'crates\.io' = ["Accept: text/html"]
